# AZURE

# Prod konfigureres via Azure (Environment Variables)
# DB_URL, DB_USER, DB_PASSWORD indtastes i Azure ved deployment

spring.application.name=EKSAMENSPROJEKT-2SEM
spring.profiles.active=prod
spring.datasource.url=${PROD_URL}
spring.datasource.username=${PROD_USER}
spring.datasource.password=${PROD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
